import { completeSimple, type Model } from "@oh-my-pi/pi-ai";
import type { ExtensionAPI, ExtensionContext } from "@oh-my-pi/pi-coding-agent";
import type { KeyId } from "@oh-my-pi/pi-tui";
import { type CompletionSnapshot, completeSnapshot, MAX_COMPLETION_TOKENS } from "./client";
import { collectPromptContext } from "./context";
import { PromptAutocompleteEditor, type RefineState } from "./editor";
import { type PickerResult, RefinePicker } from "./picker";
import { REFINE_PRESETS, RefineError, refineDraft } from "./refine";

/**
 * Inline ghost-text suggestions and one-key prompt refinement for the main prompt editor,
 * generated by small cloud models through OMP's own provider and credential machinery.
 *
 * Isolation from the agent: models are looked up read-only (`ctx.models.resolve`), requests go
 * straight to `completeSimple` with the registry's credential resolver, and nothing here calls
 * `pi.setModel`, `pi.registerProvider`, or touches roles/thinking levels. The session model can
 * therefore never be swapped or shadowed by this extension. A refined prompt is only placed in
 * the editor; sending it is always the user's Enter.
 */

/** Fast, cheap, and available to any Google Antigravity login. */
export const DEFAULT_MODEL = "google-antigravity/gemini-3.1-flash-lite";
/** Optional user overrides in `modelRoles`; absent by default. */
const AUTOCOMPLETE_ROLE = "@autocomplete";
const REFINE_ROLE = "@refine";
const COMMAND = "autocomplete";
const REFINE_WIDGET = "prompt-autocomplete-refine";
/** Chord that opens the refine picker; `OMP_PROMPT_REFINE_KEY` overrides it (read at load). */
const REFINE_KEY = (process.env.OMP_PROMPT_REFINE_KEY?.trim().toLowerCase() || "alt+e") as KeyId;
/** Custom instructions offered again at the top of the picker (per OMP process). */
const MAX_RECENT_INSTRUCTIONS = 3;

type Feature = "autocomplete" | "refine";

interface RefineChoice {
	/** Picker label (preset name or the custom text itself). */
	label: string;
	instruction: string;
}

/** `alt+e` → `Alt+E`, `ctrl+shift+e` → `Ctrl+Shift+E`. */
function keyLabel(key: string): string {
	return key
		.split(/\+(?=.)/)
		.map(part => (part.length === 1 ? part.toUpperCase() : part[0].toUpperCase() + part.slice(1)))
		.join("+");
}

function isAbort(error: unknown): boolean {
	return error instanceof Error && error.name === "AbortError";
}

export default function promptAutocomplete(pi: ExtensionAPI): void {
	let editor: PromptAutocompleteEditor | undefined;
	let enabled = true;
	/** Send project, recent files and conversation tail as background; `/autocomplete context off` stops it. */
	let withContext = true;
	/** Session-only overrides from `/autocomplete model|refine-model <spec>`. */
	const overrides: Record<Feature, string | undefined> = { autocomplete: undefined, refine: undefined };
	const resolved: Record<Feature, { spec: string; model: Model } | undefined> = { autocomplete: undefined, refine: undefined };
	let warned = false;
	let lastChoice: string | undefined;
	const recentInstructions: string[] = [];
	let refineLabel = "";

	function candidates(feature: Feature): string[] {
		const override = overrides[feature];
		if (override) return [override];
		return feature === "refine" ? [REFINE_ROLE, AUTOCOMPLETE_ROLE, DEFAULT_MODEL] : [AUTOCOMPLETE_ROLE, DEFAULT_MODEL];
	}

	function resolveModel(ctx: ExtensionContext, feature: Feature): { spec: string; model: Model } {
		const specs = candidates(feature);
		const cached = resolved[feature];
		if (cached && specs.includes(cached.spec)) return cached;
		for (const spec of specs) {
			const model = ctx.models.resolve(spec);
			if (model) {
				resolved[feature] = { spec, model };
				return resolved[feature];
			}
		}
		const override = overrides[feature];
		throw new Error(
			override
				? `model "${override}" is not available`
				: `${DEFAULT_MODEL} is not available; log in to its provider or set modelRoles.${feature === "refine" ? "refine" : "autocomplete"}`,
		);
	}

	function modelSource(feature: Feature, spec: string): string {
		if (overrides[feature]) return "session override";
		if (spec === REFINE_ROLE) return "modelRoles.refine";
		if (spec === AUTOCOMPLETE_ROLE) return "modelRoles.autocomplete";
		return "default";
	}

	function complete(ctx: ExtensionContext, snapshot: CompletionSnapshot, signal: AbortSignal): Promise<string | null> {
		const { model } = resolveModel(ctx, "autocomplete");
		const sessionId = ctx.sessionManager.getSessionId();
		const background = withContext ? collectPromptContext(ctx.sessionManager, ctx.cwd) : undefined;
		return completeSnapshot(
			(context, requestSignal) =>
				completeSimple(model, context, {
					apiKey: ctx.modelRegistry.resolver(model, sessionId),
					sessionId,
					maxTokens: MAX_COMPLETION_TOKENS,
					temperature: 0,
					// Clamped to the model's lowest effort where reasoning cannot be switched off.
					disableReasoning: true,
					hideThinkingSummary: true,
					signal: requestSignal,
				}),
			snapshot,
			signal,
			{ background },
		);
	}

	function reportError(ctx: ExtensionContext, error: unknown): void {
		if (warned) return;
		warned = true;
		const message = error instanceof Error ? error.message : "request failed";
		ctx.ui.notify(`Prompt autocomplete paused: ${message}. See /${COMMAND} status.`, "warning");
	}

	function showRefineState(ctx: ExtensionContext, state: RefineState): void {
		const theme = ctx.ui.theme;
		if (state.kind === "idle") {
			ctx.ui.setWidget(REFINE_WIDGET, undefined);
			return;
		}
		const line =
			state.kind === "refining"
				? `${theme.fg("accent", "✎ Refining prompt")}${theme.fg("muted", ` · ${refineLabel} · Esc cancel · Enter sends it unchanged`)}`
				: `${theme.fg("success", "✓ Refined")}${theme.fg("muted", ` · ${refineLabel} · Enter send · Esc restore original · ${keyLabel(REFINE_KEY)} refine again`)}`;
		ctx.ui.setWidget(REFINE_WIDGET, [line], { placement: "belowEditor" });
	}

	function rememberChoice(choice: RefineChoice, custom: boolean): void {
		lastChoice = choice.label;
		if (!custom) return;
		const existing = recentInstructions.indexOf(choice.label);
		if (existing !== -1) recentInstructions.splice(existing, 1);
		recentInstructions.unshift(choice.label);
		recentInstructions.length = Math.min(recentInstructions.length, MAX_RECENT_INSTRUCTIONS);
	}

	async function pickInstruction(
		ctx: ExtensionContext,
		draft: string,
	): Promise<{ choice: RefineChoice; custom: boolean } | undefined> {
		const presetByLabel = new Map(REFINE_PRESETS.map(preset => [preset.label, preset]));
		const options = [
			...recentInstructions
				.filter(text => !presetByLabel.has(text))
				.map(text => ({ label: text, description: "recent" })),
			...REFINE_PRESETS.map(({ label, description }) => ({ label, description })),
		];
		const result = await ctx.ui.custom<PickerResult>((tui, theme, _keybindings, done) => {
			return new RefinePicker({
				options,
				initialIndex: Math.max(0, options.findIndex(option => option.label === lastChoice)),
				draft,
				theme,
				done,
				requestRender: () => tui.requestRender(),
			});
		});
		if (!result) return undefined;
		const label = result.kind === "custom" ? result.text : result.label;
		const preset = presetByLabel.get(label);
		return { choice: { label, instruction: preset?.instruction ?? label }, custom: !preset };
	}

	async function refine(ctx: ExtensionContext): Promise<void> {
		if (!editor || !ctx.hasUI || ctx.mode !== "tui") return;
		if (editor.refineState.kind === "refining") return;
		if (!editor.getText().trim()) {
			ctx.ui.notify(`Type a prompt first, then press ${keyLabel(REFINE_KEY)} to refine it.`, "info");
			return;
		}
		let model: Model;
		try {
			model = resolveModel(ctx, "refine").model;
		} catch (error) {
			ctx.ui.notify(`Prompt refine unavailable: ${error instanceof Error ? error.message : "no model"}.`, "warning");
			return;
		}
		const picked = await pickInstruction(ctx, editor.getText());
		// The picker may outlive the editor (session switch) or the draft (cleared meanwhile).
		if (!picked || !editor) return;
		rememberChoice(picked.choice, picked.custom);
		refineLabel = picked.choice.label;
		const job = editor.beginRefine();
		if (!job) return;
		const sessionId = ctx.sessionManager.getSessionId();
		try {
			const refined = await refineDraft(
				(context, signal, maxTokens) =>
					completeSimple(model, context, {
						apiKey: ctx.modelRegistry.resolver(model, sessionId),
						sessionId,
						maxTokens,
						temperature: 0.2,
						disableReasoning: true,
						hideThinkingSummary: true,
						signal,
					}),
				{
					draft: job.draft,
					instruction: picked.choice.instruction,
					protectedTokens: job.protectedTokens,
					background: withContext ? collectPromptContext(ctx.sessionManager, ctx.cwd) : undefined,
				},
				job.signal,
			);
			if (refined === job.draft.trim()) {
				job.finish();
				ctx.ui.notify("Prompt already reads well; nothing changed.", "info");
				return;
			}
			job.apply(refined);
		} catch (error) {
			job.finish();
			if (isAbort(error)) return; // Escape, typing, or sending: the user moved on.
			const reason = error instanceof RefineError ? error.message : "request failed";
			ctx.ui.notify(`Prompt refine failed: ${reason}. Your prompt is unchanged.`, "warning");
		}
	}

	pi.on("session_start", (_event, ctx) => {
		if (!ctx.hasUI || ctx.mode !== "tui" || ctx.agent.kind !== "main") return;
		resolved.autocomplete = undefined;
		resolved.refine = undefined;
		ctx.ui.setEditorComponent((tui, theme, keybindings) => {
			editor?.dispose();
			editor = new PromptAutocompleteEditor(tui, theme, keybindings, {
				complete: (snapshot, signal) => complete(ctx, snapshot, signal),
				onError: error => reportError(ctx, error),
				onRefineStateChange: state => showRefineState(ctx, state),
			});
			editor.setAutocompleteEnabled(enabled);
			return editor;
		});
	});

	pi.on("session_shutdown", () => {
		editor?.dispose();
		editor = undefined;
	});

	pi.registerShortcut(REFINE_KEY, {
		description: "Refine the prompt draft with AI (pick an instruction; Enter still sends as-is)",
		handler: async ctx => {
			try {
				await refine(ctx);
			} catch (error) {
				// Shortcut promises are not awaited by the host; never let one escape.
				ctx.ui.notify(`Prompt refine failed: ${error instanceof Error ? error.message : "unexpected error"}.`, "error");
			}
		},
	});

	pi.registerCommand(COMMAND, {
		description:
			"Prompt suggestions and refine: on, off, status, context on|off, model <spec|default>, refine-model <spec|default>",
		getArgumentCompletions: prefix =>
			["on", "off", "status", "context on", "context off", "model default", "refine-model default"]
				.filter(item => item.startsWith(prefix.toLowerCase()))
				.map(value => ({ value, label: value })),
		handler: async (args, ctx) => {
			if (!ctx.hasUI || ctx.mode !== "tui" || !editor) return;
			const [action = "status", ...rest] = args.trim().split(/\s+/);
			const verb = action.toLowerCase();
			if (verb === "on" || verb === "off") {
				enabled = verb === "on";
				warned = false;
				editor.setAutocompleteEnabled(enabled);
			} else if (verb === "context" && (rest[0] === "on" || rest[0] === "off")) {
				withContext = rest[0] === "on";
			} else if (verb === "model" || verb === "refine-model") {
				const feature: Feature = verb === "model" ? "autocomplete" : "refine";
				const spec = rest.join(" ");
				if (!spec) {
					ctx.ui.notify(`Usage: /${COMMAND} ${verb} <provider/id|@role|default>`, "warning");
					return;
				}
				overrides[feature] = spec.toLowerCase() === "default" ? undefined : spec;
				resolved[feature] = undefined;
				if (feature === "autocomplete") {
					warned = false;
					// Drop any suggestion produced by the previous model.
					editor.setAutocompleteEnabled(false);
					editor.setAutocompleteEnabled(enabled);
				}
			} else if (verb !== "status") {
				ctx.ui.notify(
					`Usage: /${COMMAND} [on|off|status|context on|off|model <spec>|refine-model <spec>]`,
					"warning",
				);
				return;
			}
			const describe = (feature: Feature): string => {
				try {
					const { spec, model } = resolveModel(ctx, feature);
					return `${model.provider}/${model.id} (${modelSource(feature, spec)})`;
				} catch (error) {
					return `unavailable — ${error instanceof Error ? error.message : "no model"}`;
				}
			};
			ctx.ui.notify(
				[
					`Prompt autocomplete ${enabled ? "on" : "off"}: ${describe("autocomplete")}.`,
					`Refine (${keyLabel(REFINE_KEY)}): ${describe("refine")}.`,
					`Session context ${withContext ? "on" : "off"}. Agent model: ${ctx.model ? `${ctx.model.provider}/${ctx.model.id}` : "none"} — unchanged.`,
				].join(" "),
				"info",
			);
		},
	});
}
